### ISSUE TITLE
Add more improvements about i18n and l10n

### ISSUE THREAD

**Issue by macagua** [MaistrenkoAnton/django-material-admin#112]
- Add more improvements about i18n.
- Update Spanish strings without be translated.
- Update Spanish Argentina strings without be translated.

**Comment by macagua** [comment]
- Update Spanish Argentina strings without be translated, done with commit a27364f
- Update Spanish strings without be translated, done with commit d3b156e
- Add more improvements about i18n, done with commit 0d39c9c

**Comment by macagua** [comment]
Hi @MaistrenkoAnton

Can you review this pull request, if all ok can merge it?

Thank you

**Comment by MaistrenkoAnton** [comment]
Hi @macagua,
Done, thanks!

**Comment by macagua** [comment]
:D :+1:
