### ISSUE TITLE
App item overflow

### ISSUE THREAD

**Issue by jacksonperondi** [MaistrenkoAnton/django-material-admin#117]
![Capturar](https://user-images.githubusercontent.com/23363974/88828804-1a0a2100-d1a2-11ea-8706-3db7e3d75885.PNG)
First of all, thank you very much for this wonderful library.
I would like tips on how I could increase the size of the app item size to avoid overflow. Thank you

**Comment by MaistrenkoAnton** [comment]
Thanks, I will think about it on the weekend and try to fix it in new version

**Comment by MaistrenkoAnton** [comment]
Fixed in v`1.7.9`
