### ISSUE TITLE
Messages disappear too fast

### ISSUE THREAD

**Issue by fspegni** [MaistrenkoAnton/django-material-admin#132]
I would like to configure for how long a message (info, warning, debug, error, ...) could be visible to the user via the admin view. It seems other people too would like that (e.g. [https://stackoverflow.com/questions/64357116/django-display-success-messages-for-10-or-20-seconds-in-django-admin-panel](url)).

My favorite choice would be to make configurable the following behaviors:
- show the message permanently (until the user refreshes the page) in the admin view template (as in the regular admin)
- show the message on the right side bar, in a box
- show the volatile for N seconds (where N is passed through the settings).

Searching in the documentation I didn't find any of these possibilities. If some implementation is required, I can try to implement it and provide a PR (in this case I just ask a hint on where to look, which components or templates extend)

**Comment by MaistrenkoAnton** [comment]
Thanks for your suggestion, I still thinking about it...

Messages are implemented via materialcss toast
https://materializecss.com/toasts.html

I think maybe it makes sense to increase duration time, and add also configuration value to project settings
