### ISSUE TITLE
LookupError: No installed app with label 'admin'.

### ISSUE THREAD

**Issue by imtiazAyon** [MaistrenkoAnton/django-material-admin#155]
Installed material-admin like the Quick start said. runserver runs fine. I can view and work with the admin site. But makemigrations throws this error "LookupError: No installed app with label 'admin'." over this line in urls.py, 
`path('admin/', admin.site.urls),`
Added material and material.admin in installed apps and imported admin from django.contrib. So what should I do?

**Comment by IgnacioKase** [comment]
Having the same error here, I replaced

`'django.contrib.admin',`

with

`'material.admin',`

and I got the same error

**Comment by imtiazAyon** [comment]
Made a mistake. While switching environment I thought I had Django 3.2 installed but it was 2.2 that was why I was getting the error. Disappeared after I upgraded Django to 3.2
