### ISSUE TITLE
Thirdparty integrations

### ISSUE THREAD

**Issue by cyberbudy** [MaistrenkoAnton/django-material-admin#31]
Do you plan making(describing) integration with some other thirdparty packages like parler, filer or any tree-model?

**Comment by MaistrenkoAnton** [comment]
Yes, I'm going to make integration with "mptt", maybe with "filer" and other. But for now first of all I concentrated on my own planned features related to materialize. And after that I will think about integration with the thirdparties.

**Comment by cyberbudy** [comment]
Maybe you can publish your next planning features to help you ?

**Comment by MaistrenkoAnton** [comment]
My nearest planned features are described in readme.
