### ISSUE TITLE
unregistering django default user and user_group form admin

### ISSUE THREAD

**Issue by AhmadiWork** [MaistrenkoAnton/django-material-admin#33]
in normal django admin, i unregister django base user and user_group by this code:

`admin.site.unregister(User)`
`admin.site.unregister(Group)`

but in django-material-admin it not working :(

how can i do this in django-material-admin?

**Comment by MaistrenkoAnton** [comment]
Can you try?  

from django.material.sites import site
from django.contrib.auth.models import User,  Group 

site.unregister(User)
site.unregister(Group)

**Comment by AhmadiWork** [comment]
it worked
thank you
