### ISSUE TITLE
adding inline-related-card

### ISSUE THREAD

**Issue by AhmadiWork** [MaistrenkoAnton/django-material-admin#34]
hi
how can i create inline-related-card like PERSONS section in this link?

http://ec2-35-157-197-184.eu-central-1.compute.amazonaws.com/admin/countries/country/1/change/

**Comment by MaistrenkoAnton** [comment]
It's StackedInline 
https://github.com/MaistrenkoAnton/django-material-admin/blob/master/app/demo/countries/admin.py

**Comment by MaistrenkoAnton** [comment]
from django.contrib import admin

from demo.countries.models import Country, Person, ProxyPerson
from material.decorators import register
from material.options import MaterialModelAdmin


class PersonInline(admin.StackedInline):
    model = Person
    ordering = ('id',)
    extra = 0


@register(Country)
class CountryAdmin(MaterialModelAdmin):
    list_display = ('name', 'created', 'modified')
    inlines = [PersonInline]
    icon_name = 'location_city'
    search_fields = ('name',)

**Comment by AhmadiWork** [comment]
so thanks man :+1:
