### ISSUE TITLE
Admin TabularInline does not show the delete checkbox

### ISSUE THREAD

**Issue by Luis-Palacios** [MaistrenkoAnton/django-material-admin#35]
Hello! Very nice looking Django admin theme!  Thank you for your hard work.

I have found that the Tabular Inline does not show the delete checkbox, I seem to have my configurations correctly

```python
class ChoiceInline(admin.TabularInline):
    model = Choice
    extra = 2
    fields = ['choice_text', 'votes']
    readonly_fields = ['votes']


@register(Question)
class QuestionAdmin(MaterialModelAdmin):
    icon_name = 'question_answer'
    list_display = ('question_text', 'choices_count', 'total_votes',
                    'pub_date')
    search_fields = ['question_text']
    inlines = [ChoiceInline]

    def get_changeform_initial_data(self, request):
        return {'pub_date': timezone.now()}
```
But no delete checkbox
![image](https://user-images.githubusercontent.com/4844997/61190116-4a912280-a654-11e9-9e78-b5006b76046c.png)

However, If I change to StackedInline the delete works
![image](https://user-images.githubusercontent.com/4844997/61190124-6bf20e80-a654-11e9-8851-fa2d99862a91.png)

Am I doing something wrong? or have I found a bug?

**Comment by MaistrenkoAnton** [comment]
Hello,  I think the reason could be cached script from previous version of package. Could you try ctrl + F5? 
If no,  then I will try to reproduce today and fix.

**Comment by Luis-Palacios** [comment]
I tried ctrl + f5 but the issue remains

**Comment by MaistrenkoAnton** [comment]
Bug fixed in v.1.1.19. Please reinstall using new version. It should work now
![joxi_screenshot_1563174870216](https://user-images.githubusercontent.com/15648919/61200266-84f8cf00-a6e9-11e9-9a41-8d9c4a31a897.png)

**Comment by Luis-Palacios** [comment]
Thank you.

Now it's working correctly
