### ISSUE TITLE
Quick start don't work

### ISSUE THREAD

**Issue by ovt00** [MaistrenkoAnton/django-material-admin#37]
I try install django-material-admin, but I don't understand what is the app "persons" ? Why need unregister User and Group models? Is it necessary?
I can't go to 3 point.

**Comment by MaistrenkoAnton** [comment]
1.  Persons is just an example,  you can register any you model in any app. 
2. Unregister is optional.  I just pointed how to unregister models if they should be unregistered from admin interface.

**Comment by ovt00** [comment]
Здравствуйте.
Спасибо за ответ.
Если я просто регистрирую свою модель в админке, то получаю ошибку:
Invalid template library specified. ImportError raised when trying to load 'material.templatetags.material_form_internal': cannot import name 'SelectDateWidget'

25 июля 2019, 00:59:40, от Anton <notifications@github.com>:

Persons is just an example, you can register any you model in any app. Unregister is optional. I just pointed how to unregister models if they should be unregistered from admin interface. —

**Comment by MaistrenkoAnton** [comment]
Добрый день. 
Данная ошибка не относится к 'django-material-admin' и приходит из другого пакета https://github.com/viewflow/django-material/blob/master/material/templatetags/material_form_internal.py. 

Похоже вы не тот package устанавливаете.

**Comment by MaistrenkoAnton** [comment]
Попробуйте установить последнюю версию пакета - `1.3.1`, конфликт должен быть уже исправлен, и проделайте шаги согласно обновленной инстукции:
https://github.com/MaistrenkoAnton/django-material-admin

**Comment by ovt00** [comment]
Добрый вечер(день).
Только сегодня добрался попробывать и все запустилось и работает. 
Спасибо, это круто.
В последнее время и использую админку от grappelli, скажите, в Вашей админке есть какие-то ограничения или работает по-крайне мере как стандартная?

Олег

25 июля 2019, 12:39:27, от Anton <notifications@github.com>:

Попробуйте установить последнюю версию пакета - 1.3.1, конфликт должен быть уже исправлен, и проделайте шаги согласно обновленной инстукции:
https://github.com/MaistrenkoAnton/django-material-admin

**Comment by MaistrenkoAnton** [comment]
Добрый день, 
пока что реализован функционал для стандартной админки, для различного вида популярных third-party packages я планирую поддержку немного позже.

**Comment by ovt00** [comment]
Доброго дня.
Спасибо за Ваш труд.
Заметил, что при использовании fieldsets, несмотря на то, что указываю отображать в одной строке, , например, 
    fieldsets = (
        (_('Заголовок'), {
            'fields': (
                ('domain'', 'email',),
            ),
        },),
    )
отображение каждого поля все равно происходит на отдельных строках.

Поправьте в следующем версии.

Олег.

30 июля 2019, 09:47:14, от Anton <notifications@github.com>:

Добрый день,
пока что реализован функционал для стандартной админки, для различного вида популярных third-party packages я планирую поддержку немного позже.

**Comment by MaistrenkoAnton** [comment]
Добрый день,
Спасибо, должно быть поправлено в v1.4.4

чт, 29 авг. 2019 г. в 00:02, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
У меня стоит v1.4.5

29 августа 2019, 09:55:20, от Anton <notifications@github.com>:

Добрый день, 
Спасибо, должно быть поправлено в v1.4.4 

чт, 29 авг. 2019 г. в 00:02, Oleg Tolmachev <notifications@github.com>:

**Comment by MaistrenkoAnton** [comment]
В версии v1.4.5 должно быть пофикшено,
у Вас все еще репродюсится проблема ?

чт, 29 авг. 2019 г. в 22:18, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Да

30 августа 2019, 10:19:21, от Anton <notifications@github.com>:

В версии v1.4.5 должно быть пофикшено, 
у Вас все еще репродюсится проблема ? 

чт, 29 авг. 2019 г. в 22:18, Oleg Tolmachev <notifications@github.com>:

**Comment by MaistrenkoAnton** [comment]
Хм, проверяю - не репродюсится у меня (Поля собираются в одну стоку).
Может быть кэш - попробуйте ctrl + F5

пт, 30 авг. 2019 г. в 11:06, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Не помогает. Если же писать типа:
fieldsets = ( 
    (_('Заголовок'), { 
    'fields': ( 
        ('domain'',), 
        ('email',), 
        ), 
     },), 
    ) 
то между строчками увеличивается расстояние.
И, кстати, в admin.py, прописывая icon_name, иконка не появляется. В apps.py - все ок.


30 августа 2019, 11:35:44, от Anton <notifications@github.com>:

Хм, проверяю - не репродюсится у меня (Поля собираются в одну стоку). 
Может быть кэш - попробуйте ctrl + F5 

пт, 30 авг. 2019 г. в 11:06, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Извини, у меня версия 1.4.1 была(не туда смотрел), 

30 августа 2019, 11:35:44, от Anton <notifications@github.com>:

Хм, проверяю - не репродюсится у меня (Поля собираются в одну стоку). 
Может быть кэш - попробуйте ctrl + F5 

пт, 30 авг. 2019 г. в 11:06, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Здравствуйте.
Обновился до последней версии, до этого стояла версия 1.4.5 и не могу переопределить site.favicon и аналогичные параметры, которые теперь задаются в settings. Ранее я в urls.py их переопределял, брав значения с БД. 
Как сейчас можно это сделать?

Спасибо за Вашу работу.

Олег

31 августа 2019, 11:08:26, от Oleg <ovt00@ukr.net>:

Извини, у меня версия 1.4.1 была(не туда смотрел), 

30 августа 2019, 11:35:44, от Anton <notifications@github.com>:

Хм, проверяю - не репродюсится у меня (Поля собираются в одну стоку). 
Может быть кэш - попробуйте ctrl + F5 

пт, 30 авг. 2019 г. в 11:06, Oleg Tolmachev <notifications@github.com>:

**Comment by MaistrenkoAnton** [comment]
Добрый вечер,
Теперь кофигурациями нужно управлять в файле сеттингов,

```

MATERIAL_ADMIN_SITE = {
    'HEADER':  _('Your site header'),  # Admin site header
    'TITLE':  _('Your site title'),  # Admin site title
    'FAVICON':  'path/to/favicon',  # Admin site favicon (path to
static should be specified)
    'MAIN_BG_COLOR':  'color',  # Admin site main color, css color
should be specified
    'MAIN_HOVER_COLOR':  'color',  # Admin site main hover color, css
color should be specified
    'PROFILE_PICTURE':  'path/to/image',  # Admin site profile picture
(path to static should be specified)
    'PROFILE_BG':  'path/to/image',  # Admin site profile background
(path to static should be specified)
    'LOGIN_LOGO':  'path/to/image',  # Admin site logo on login page
(path to static should be specified)
    'LOGOUT_BG':  'path/to/image',  # Admin site background on
login/logout pages (path to static should be specified)
    'SHOW_THEMES':  True,  #  Show default admin themes button
    'TRAY_REVERSE': True,  # Hide object-tools and
additional-submit-line by default
    'NAVBAR_REVERSE': True,  # Hide side navbar by default
    'SHOW_COUNTS': True, # Show instances counts for each model
    'APP_ICONS': {  # Set icons for applications(lowercase), including
3rd party apps, {'application_name': 'material_icon_name', ...}
        'sites': 'send',
    },
    'MODEL_ICONS': {  # Set icons for models(lowercase), including 3rd
party models, {'model_name': 'material_icon_name', ...}
        'site': 'contact_mail',
    }
}
```


ср, 15 янв. 2020 г. в 23:51, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Это я понял, но там я не смогу прописать значениями их базы

15 января 2020, 23:55:04, от Anton <notifications@github.com>:

Добрый вечер, 
Теперь кофигурациями нужно управлять в файле сеттингов, 

``` 

MATERIAL_ADMIN_SITE = { 
'HEADER': _('Your site header'), # Admin site header 
'TITLE': _('Your site title'), # Admin site title 
'FAVICON': 'path/to/favicon', # Admin site favicon (path to 
static should be specified) 
'MAIN_BG_COLOR': 'color', # Admin site main color, css color 
should be specified 
'MAIN_HOVER_COLOR': 'color', # Admin site main hover color, css 
color should be specified 
'PROFILE_PICTURE': 'path/to/image', # Admin site profile picture 
(path to static should be specified) 
'PROFILE_BG': 'path/to/image', # Admin site profile background 
(path to static should be specified) 
'LOGIN_LOGO': 'path/to/image', # Admin site logo on login page 
(path to static should be specified) 
'LOGOUT_BG': 'path/to/image', # Admin site background on 
login/logout pages (path to static should be specified) 
'SHOW_THEMES': True, # Show default admin themes button 
'TRAY_REVERSE': True, # Hide object-tools and 
additional-submit-line by default 
'NAVBAR_REVERSE': True, # Hide side navbar by default 
'SHOW_COUNTS': True, # Show instances counts for each model 
'APP_ICONS': { # Set icons for applications(lowercase), including 
3rd party apps, {'application_name': 'material_icon_name', ...} 
'sites': 'send', 
}, 
'MODEL_ICONS': { # Set icons for models(lowercase), including 3rd 
party models, {'model_name': 'material_icon_name', ...} 
'site': 'contact_mail', 
} 
} 
``` 


ср, 15 янв. 2020 г. в 23:51, Oleg Tolmachev <notifications@github.com>:

**Comment by MaistrenkoAnton** [comment]
Я понял, тогда нужно делать так в файле url.py:

from django.contrib import admin

admin.site.profile_picture =
'https://freelancw-dev.s3.amazonaws.com/static/admin/profile_bg.png'

и так далее

с этими переменными

admin.site.favicon = None
admin.site.main_bg_color = None
admin.site.main_hover_color = None
admin.site.profile_picture = None
admin.site.profile_bg = None
admin.site.login_logo = None
admin.site.logout_bg = None
admin.site.show_themes = False
admin.site.show_counts = False

**Comment by MaistrenkoAnton** [comment]
И здесь используйте значения как и раньше делали

чт, 16 янв. 2020 г. в 00:21, Anton Maistrenko <it2015maistrenko@gmail.com>:

> Я понял, тогда нужно делать так в файле url.py:
>
> from django.contrib import admin
>
> admin.site.profile_picture = 'https://freelancw-dev.s3.amazonaws.com/static/admin/profile_bg.png'
>
> и так далее
>
> с этими переменными
>
> admin.site.favicon = None
> admin.site.main_bg_color = None
> admin.site.main_hover_color = None
> admin.site.profile_picture = None
> admin.site.profile_bg = None
> admin.site.login_logo = None
> admin.site.logout_bg = None
> admin.site.show_themes = False
> admin.site.show_counts = False
>
>

**Comment by ovt00** [comment]
Здравствуйте.
Подскажите, как подружить material-admin с django-modeltranslation (https://django-modeltranslation.readthedocs.io/en/latest/).

Олег

16 января 2020, 00:23:02, от Anton <notifications@github.com>:

И здесь используйте значения как и раньше делали 

чт, 16 янв. 2020 г. в 00:21, Anton Maistrenko <it2015maistrenko@gmail.com>:

**Comment by MaistrenkoAnton** [comment]
>
> Добрый день!


ModelTranslationOptions отрабатывает корректно и добавляет поля в админке
соответственно установленным языкам.

[image: joxi_screenshot_1580038135222.png]

Какой функционал конкретно не работает, можете описать ?

**Comment by ovt00** [comment]
Не работает при использовании https://django-modeltranslation.readthedocs.io/en/latest/admin.html#using-tabbed-translation-fields

![image](https://user-images.githubusercontent.com/6506921/73135129-8f583600-4047-11ea-8a51-f3a444faddb5.png)

**Comment by MaistrenkoAnton** [comment]
Опишите что работает неверно.  В материал версии работает идентично как и в
нативной версии админки

[image: joxi_screenshot_1580056164295.png]

[image: joxi_screenshot_1580056122377.png]

вс, 26 янв. 2020 г. в 14:26, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Не работает использование Tabs для переключения переводимых полей, ссылка из документации modeltranslation: https://django-modeltranslation.readthedocs.io/en/latest/admin.html#using-tabbed-translation-fields

Cрин как сейчас это выглядит отправил в прошлом сообщении.



26 января 2020, 18:32:46, от Anton <notifications@github.com>:

Опишите что работает неверно. В материал версии работает идентично как и в 
нативной версии админки 

[image: joxi_screenshot_1580056164295.png] 

[image: joxi_screenshot_1580056122377.png] 

вс, 26 янв. 2020 г. в 14:26, Oleg Tolmachev <notifications@github.com>:

**Comment by MaistrenkoAnton** [comment]
Хорошо. ближайшее время поправлю.

вс, 26 янв. 2020 г. в 22:18, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Добрый день.
Увидел коммит о Tabbed modeltranslations., установил, но у меня ничего не изменилось



26 января 2020, 22:18:11, от Oleg <ovt00@ukr.net>:

Не работает использование Tabs для переключения переводимых полей, ссылка из документации modeltranslation: https://django-modeltranslation.readthedocs.io/en/latest/admin.html#using-tabbed-translation-fields

Cрин как сейчас это выглядит отправил в прошлом сообщении.



26 января 2020, 18:32:46, от Anton <notifications@github.com>:

Опишите что работает неверно. В материал версии работает идентично как и в 
нативной версии админки 

[image: joxi_screenshot_1580056164295.png] 

[image: joxi_screenshot_1580056122377.png] 

вс, 26 янв. 2020 г. в 14:26, Oleg Tolmachev <notifications@github.com>:

**Comment by MaistrenkoAnton** [comment]
добрый день,  попробуйте почистить кэш

вт, 4 фев 2020, 22:26 Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Да нет, у меня ошибка в JS:

04 февраля 2020, 22:31:01, от Anton <notifications@github.com>:

добрый день, попробуйте почистить кэш 

вт, 4 фев 2020, 22:26 Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Добрый день.
Спасибо, modeltranslation работает как надо.
1. Выявилась проблема с django-mppt. Если использовать класс DraggableMPTTAdmin, то все работает номально. А вот если MPTTModelAdmin, то в листе не выводится элементы action-checkbox, Причина: не хватает span, как при DraggableMPTTAdmin
2. При использовании slug полей и при вводе чего-то в population поле, Label slug-поля не поднимается и соответственно текст в slug-поле наезжает на метку
3. Нельзя ли сделать в классе ModelAdmin возможность регулировать ширину полей в в одном row, сейчас ширина делится пропорционально количеству выводимых полей в строке.

Спасибо.

04 февраля 2020, 22:31:01, от Anton <notifications@github.com>:

добрый день, попробуйте почистить кэш 

вт, 4 фев 2020, 22:26 Oleg Tolmachev <notifications@github.com>: 

> Добрый день. 
> Увидел коммит о Tabbed modeltranslations., установил, но у меня ничего не 
> изменилось 
> 
> 
>

**Comment by MaistrenkoAnton** [comment]
Добрый день
1. Проверю попозже взаимодействие с MPTT
2. Пофикшено с `v1.6.44`
3. Пока не уверен что это будет реализовано.

сб, 8 февр. 2020 г. в 01:28, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Здравствуйте.Будет ли продолжаться работа над проектом?

Олег

--- Исходное сообщение ---
От кого: "Oleg" <ovt00@ukr.net>
Дата: 8 февраля 2020, 01:26:51

Добрый день.
Спасибо, modeltranslation работает как надо.
1. Выявилась проблема с django-mppt. Если использовать класс DraggableMPTTAdmin, то все работает номально. А вот если MPTTModelAdmin, то в листе не выводится элементы action-checkbox, Причина: не хватает span, как при DraggableMPTTAdmin
2. При использовании slug полей и при вводе чего-то в population поле, Label slug-поля не поднимается и соответственно текст в slug-поле наезжает на метку
3. Нельзя ли сделать в классе ModelAdmin возможность регулировать ширину полей в в одном row, сейчас ширина делится пропорционально количеству выводимых полей в строке.

Спасибо.

04 февраля 2020, 22:31:01, от Anton <notifications@github.com>:

добрый день, попробуйте почистить кэш 

вт, 4 фев 2020, 22:26 Oleg Tolmachev <notifications@github.com>: 

> Добрый день. 
> Увидел коммит о Tabbed modeltranslations., установил, но у меня ничего не 
> изменилось 
> 
> 
>

**Comment by ovt00** [comment]
Здравствуйте.
Я мспользую Ваш django-material-admin. И почему-то появилась проблема в хроме(в файрфоксе проблем нет). А именно, все работает как надо, но стоит включить инспектор, то на любой странице при попытке перегрузить ее, браузер как бы подвисает, запрос не отправляется и чере знекоторое время появляется следующая ошибка:

не можете подсказать, что это может быть?


Заранее спасибо,

Олег

**Comment by ovt00** [comment]
Здравствуйте,не сразу обратил внимание, о в инлайн формах при нажатии "Add another..." не отображаются табы, на сколько я понял не вызывается tabbed_translation_fields.js

Не подскажите, как это можно поправить?

Заранее спасибо,
Олег

**Comment by MaistrenkoAnton** [comment]
Добрый день,
Да там нужно править скрипты в библиотеке, постараюсь найти время на
выходных и поправить
Спасибо

вс, 12 июл. 2020 г. в 21:09, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Здравствуйте.
Спасибо.
Может добавите поддержку mptt и tabbed_admin, в прикрепленных файлах модифицированные html, которые я сделал, чтобы эти 2 приложения нормально работали

Олег

14 июля 2020, 10:24:45, от Anton <notifications@github.com>:



Добрый день, 
Да там нужно править скрипты в библиотеке, постараюсь найти время на 
выходных и поправить 
Спасибо 

вс, 12 июл. 2020 г. в 21:09, Oleg Tolmachev <notifications@github.com>:

**Comment by ovt00** [comment]
Привет.
При использовании TranslationStackedInline не пофиксилось.



14 июля 2020, 10:24:45, от Anton <notifications@github.com>:



Добрый день, 
Да там нужно править скрипты в библиотеке, постараюсь найти время на 
выходных и поправить 
Спасибо 

вс, 12 июл. 2020 г. в 21:09, Oleg Tolmachev <notifications@github.com>:
