### ISSUE TITLE
Admin fieldsets with collapse class are not working

### ISSUE THREAD

**Issue by pablop94** [MaistrenkoAnton/django-material-admin#40]
Hi! 
I've been investigating this issue for the last days with no luck.

I've a ModelAdmin with fieldsets attribute set. I've included the collapse class in order to hide those fields as default.

When I installed the django-material-admin, those fields are not working. 
Inline models with collapse are working just fine, but the fieldsets are not attached to the collapse.js file via click event.

Maybe you can help me to see which are the involved files and check if I can fix it, otherwise I think that I'll not be able to find it.

![image](https://user-images.githubusercontent.com/20630332/63875435-d60f0a80-c999-11e9-83b6-e3cc4692d762.png)

https://justbeamit.com/mjbpy (video of the issue)

Regards

**Comment by MaistrenkoAnton** [comment]
Hi,
It should work properly in new version (1.4.3).
Thanks.

**Comment by Vulum** [comment]
Hi @MaistrenkoAnton , I have django-material-admin version 1.7.16 but still @pablop94's issue exist....
