### ISSUE TITLE
Static URLs broken for Custom Storages

### ISSUE THREAD

**Issue by aniruddha-adhikary** [MaistrenkoAnton/django-material-admin#42]
When using a custom storage engine Boto (S3) or Google Cloud Storage with signed URLs, the static file URLS break as in templates, the URLs aren't joined properly.

**Example:**

**Expected:**
```
https://s3.amazon.com/static/image.png?AWSCredentials=xyz
```

**Actual Implementation:**
```
https://s3.amazon.com/static/?AWSCredentials=xyzimage.png
```

The filename gets appended after the query string. Which results in such signed URLs not working.  As templates are declared like,

```{% static 'material/admin/images/' %}login-logo-{{ current_theme }}.jpg```

I recon a fix would be something like,
```{% static 'material/admin/images/login-logo-'|add:current_theme|add:'.jpg' %}```

**Comment by MaistrenkoAnton** [comment]
Thanks,
Should be fixed in v1.4.6
