### ISSUE TITLE
Customising theme colours

### ISSUE THREAD

**Issue by leandroviajando** [MaistrenkoAnton/django-material-admin#44]
Love it, admin page looks actually really nice now!

Is it possible to customise the colour scheme? From my Django app I mean. I'd like to change the blue to dark yellow.

Thank you!

**Comment by MaistrenkoAnton** [comment]
Hello
Yes, it's possible from `1.4.8` version.
So in main `urls.py` config file add admin site configuration variables:

site.main_bg_color = 'green'                               
site.main_hover_color = 'yellow'
site.profile_picture = staticfiles('path/to/image')
site.profile_bg = staticfiles('path/to/background')

Like in example - 
https://github.com/MaistrenkoAnton/django-material-admin/blob/master/app/demo/urls.py

And the result for default theme could be: 

![joxi_screenshot_1571484417194](https://user-images.githubusercontent.com/15648919/67144178-991a1280-f27c-11e9-8749-0da49d07176d.png)

**Comment by leandroviajando** [comment]
Hi Anton,

I added to my ```urls.py``` the following:
```
site.site_header = _('custom')
site.index_title = _('custom')
site.site_title = _('custom')
site.favicon = static('logo.png')
site.main_bg_color = 'green'
site.main_hover_color = 'yellow'
site.profile_picture = static('logo.png')
```

The site_header, index_title, site_title and favicon are indeed updated. But the main_bg_color, main_hover_color and profile_picture remain unchanged...

**Comment by MaistrenkoAnton** [comment]
Maybe you have an old version of pip
try  "pip install django-material-admin -U"

**Comment by leandroviajando** [comment]
Still the same. I'm using pipenv for the dependencies of this project. But what I find surprising is that the first four work and the last three don't

**Comment by MaistrenkoAnton** [comment]
What version of `django-material-admin` is installed on your environment ?

**Comment by leandroviajando** [comment]
v1.4.8

In the browser, I was able to change the css

**Comment by MaistrenkoAnton** [comment]
hmm, maybe cache -> control + F5 ?

**Comment by leandroviajando** [comment]
already tried, that logs me out but after logging back in still the same

**Comment by leandroviajando** [comment]
SOLVED:
- It only works with the default theme 🤦‍♂️
- You can only update the profile_picture if you also update the profile_bg

Thanks for your help Anton!

**Comment by leandroviajando** [comment]
Another small issue: Is it possible to update login.html and logout.html as well when changing the site config?

When logging out, the favicon and site_title are still displayed correctly - as set in the config.

The main_bg_color, main_hover_color, profile_picture, profile_bg are only updated in index.html, however

**Comment by leandroviajando** [comment]
<img width="1345" alt="Captura de pantalla 2019-10-19 a las 21 12 07" src="https://user-images.githubusercontent.com/47894245/67150246-7526f300-f2b5-11e9-9eb6-766fec2d2bf7.png">

Thanks so much for your help!

**Comment by MaistrenkoAnton** [comment]
I just release the latest version `1.5.0` and I enhanced the themes implementation.
I extended variables:

**site.site_header = _('Demo')
site.site_title = _('Demo')
site.favicon = staticfiles('demo.png')
site.main_bg_color = 'green'
site.main_hover_color = 'yellow'
site.profile_picture = staticfiles('profile-background.jpeg')
site.profile_bg = staticfiles('profile-background.jpeg')
site.login_logo = staticfiles('profile-background.jpeg')
site.logout_bg = staticfiles('profile-background.jpeg')** 

Thanks for your suggestions, any feedback will be appreciated.

**Comment by leandroviajando** [comment]
Thanks so much! Looks perfect now 👌
