### ISSUE TITLE
icon_name

### ISSUE THREAD

**Issue by leandroviajando** [MaistrenkoAnton/django-material-admin#45]
Hi Anton,

Under point 6 of the README, you use icon_name = 'person' to change the icon of the model.

Under point 7, there are a number of different options visible (for Countries, Documents, Periods, etc.). Could you add the possible options for icon_name to the documentation please?

Thank you!

**Comment by MaistrenkoAnton** [comment]
Hi, 
I added sources in point 6 as:
https://materializecss.com/icons.html
https://material.io/resources/icons/?style=baseline

**Comment by leandroviajando** [comment]
thanks! could be useful to include the links in the readme 😊
