### ISSUE TITLE
ModelAdmin methods

### ISSUE THREAD

**Issue by leandroviajando** [MaistrenkoAnton/django-material-admin#47]
https://docs.djangoproject.com/en/2.2/ref/contrib/admin/actions/#actions-as-modeladmin-methods

```
self.message_user(request, "test")
```
doesn't display any message upon applying an action. I am following the example from the documentation (please see second example of the section in the link above). Only difference is the example in the docs inherits from admin.ModelAdmin whereas I use MaterialModelAdmin. Are action messages not supported?

**Comment by leandroviajando** [comment]
https://www.google.com/search?tbm=isch&source=hp&biw=1354&bih=685&ei=5dzCXb7YMMXjgwfM1KW4Dg&q=django+admin&oq=django+admin&gs_l=img.3..0l10.1357.2546..2775...0.0..0.85.795.12......0....1..gws-wiz-img.......0i10.OVKi0l2gw3Y&ved=0ahUKEwj-3oX56dXlAhXF8eAKHUxqCecQ4dUDCAY&uact=5#imgrc=HX-T1QcUKT-hgM

Also, recent actions are not displayed. How can I add this?

Many thanks!

**Comment by leandroviajando** [comment]
> https://www.google.com/search?tbm=isch&source=hp&biw=1354&bih=685&ei=5dzCXb7YMMXjgwfM1KW4Dg&q=django+admin&oq=django+admin&gs_l=img.3..0l10.1357.2546..2775...0.0..0.85.795.12......0....1..gws-wiz-img.......0i10.OVKi0l2gw3Y&ved=0ahUKEwj-3oX56dXlAhXF8eAKHUxqCecQ4dUDCAY&uact=5#imgrc=HX-T1QcUKT-hgM

Just found this is visible under 'History' for individual objects

**Comment by MaistrenkoAnton** [comment]
Hi, 
For adding messages you can always use

from django.contrib import messages
messages.add_message(request, messages.SUCCESS, 'message text', fail_silently=True)

I'm curious why self.message_user(request, "test") does not work. I'm going to check the source and figure it out. I'll notify you.

Thanks for reporting.

**Comment by MaistrenkoAnton** [comment]
So I checked

Now working only

self.message_user(request, "successfully marked as published.", messages.SUCCESS)
self.message_user(request, "successfully marked as published.", messages.WARNING)

Support of INFO and ERROR I'm going to add in the near future.

**Comment by MaistrenkoAnton** [comment]
I added INFO and ERROR.

So update package version to `1.5.1`, clean cache and you can use any of this message types so far:

        self.message_user(request, "Published INFO.")
        self.message_user(request, "Published INFO.", messages.INFO)
        self.message_user(request, "Published ERROR.", messages.ERROR)
        self.message_user(request, "Published SUCCESS.", messages.SUCCESS)
        self.message_user(request, "Published WARNING.", messages.WARNING)

**Comment by leandroviajando** [comment]
Perfect, thank you! All messages work now.
