### ISSUE TITLE
Checkbox in a Tabular Inline form doesn't work

### ISSUE THREAD

**Issue by R4trtry** [MaistrenkoAnton/django-material-admin#55]
Seems the material checkbox is not implemented in `admin/edit_inline/tabular.html`
And the original checkbox is hidden from the view. So where a checkbox should be in the inline form, it shows just blank. 

I really like how the package just works as a drop in replacement of the native admin, but I'm kinda blocked by this feature. Please help 🙏

**Comment by h3adHunter** [comment]
Hi, im experiencing this too, i "kindof fix it" with a workaround. Edited the materialize.min.css but is not a happy solution cause ive lost that beautiful checkbox.
A little help would be really appreciated. :)

**Comment by MaistrenkoAnton** [comment]
Hi, Fixed in v.1.6.9

Thanks for the report.

**Comment by h3adHunter** [comment]
Thanks Anton, its working great!
