### ISSUE TITLE
Firefox - Grid view from Home goes crazy

### ISSUE THREAD

**Issue by h3adHunter** [MaistrenkoAnton/django-material-admin#56]
Hi Anton, seems like the responsive grid from de Home of the Admin Panel is not working right on Firefox. Ive tested on Chrome and Opera and it works fine.
However on Firefox it changes when i pass the mouse above the different panels.
![firefox-issue-1](https://user-images.githubusercontent.com/31490812/70733487-2f9d0a00-1ce9-11ea-9453-9740d4370865.jpg)
![firefox-issue-2](https://user-images.githubusercontent.com/31490812/70733488-3035a080-1ce9-11ea-99e7-9831bc7615f4.jpg)

Really weird, i dont know what to do.

Thanks for everything!

**Comment by MaistrenkoAnton** [comment]
Hi, fixed in `v1.6.10`

Thanks for the report.
