### ISSUE TITLE
Feature: Home Page Logo

### ISSUE THREAD

**Issue by h3adHunter** [MaistrenkoAnton/django-material-admin#59]
Hi Anton, I was trying to put an image between the side menu button and the site's header.
![imagen](https://user-images.githubusercontent.com/31490812/70871477-21b3e700-1f7e-11ea-9fa0-8cebb993c1aa.png)

Is there a way to achieve that?

Thanks

**Comment by MaistrenkoAnton** [comment]
Hi, you can try to use `mark_safe`
Like
from django.utils.safestring import mark_safe
MATERIAL_ADMIN_SITE = {
'HEADER':  mark_safe('<img height="40" style="margin-left: -30px;" width="40" src="/static/profile-background.jpeg"> Donde comemos | Panel de ...'),
...
}

**Comment by h3adHunter** [comment]
Thank you Anton, i would like to make this as a setting later so when i have some time i'll make a PR with this feature.
Its a good solution, for now.
