### ISSUE TITLE
Some Spanish Translations Missing

### ISSUE THREAD

**Issue by h3adHunter** [MaistrenkoAnton/django-material-admin#60]
Hi Anton, for example, the button All Actions hasn't has a translation in Spanish. Also the Tool's Panel, and so on.
I've override the .po file from my project Django but that will be erased when i install/upgrade django.

Any suggestions for adding that Strings to a custom Translation into my project?

Thanks in advance

**Comment by MaistrenkoAnton** [comment]
Hi, 
I've added the Spanish locale in `v1.6.16`.
Please try it, and let me know if you have any related issues with translation.

**Comment by h3adHunter** [comment]
Hi, 
Still experiencing some issues, think the spanish locale was being used cause some words were translating correctly. But i guess that the problem is it doesnt have some words that you add to the admin panel with the material plugin, for example the following:
![imagen](https://user-images.githubusercontent.com/31490812/71101405-6bc2e580-2195-11ea-9055-396bde8826da.png)
![imagen](https://user-images.githubusercontent.com/31490812/71101498-957c0c80-2195-11ea-8803-3b4806835662.png)

_The "All actions" one is the most important cause the tools panel can be hidden._

**I found a workaround** adding the messages to the file django.po of my locale in the python lib folder of my virtual env 'lib/python3.5/site-packages/django/contrib/admin/locale/es_AR/LC_MESSAGES/django.po'.
Here i can add my missing translation like this:
...
msgid "All actions"
msgstr "Todas las acciones"

and then on the console: **python manage.py compilemessages**

**Comment by MaistrenkoAnton** [comment]
Hi, 
Strange, using the `v1.6.17` the tools and All actions are translated from my side and it looks like
![joxi_screenshot_1576703157508](https://user-images.githubusercontent.com/15648919/71123517-8162fa00-21eb-11ea-98b6-994f6a339fe7.png)

Yes, Your workaround will work as you redefined the compiled translations. And I think the reason is that you are using `es_AR` locale. I'll add it to the next version.

**Comment by h3adHunter** [comment]
Upgrade to 1.6.18 and its working fine now, thanks Anton.
