### ISSUE TITLE
Feature: Settings for ObjectTools and AdditionalSubmitLine

### ISSUE THREAD

**Issue by h3adHunter** [MaistrenkoAnton/django-material-admin#61]
Hi Anton, i was wondering if is there any way to set this two features to be hide by default.

Thanks in advance.

**Comment by MaistrenkoAnton** [comment]
Hi,
In version `1.6.13` added config, which hide these tools by default:
'TRAY_REVERSE':  True
You can check in readme documentation

**Comment by MaistrenkoAnton** [comment]
Hi, in `v.1.6.14` added config 'TRAY_REVERSE': True
You can check it in readme docs.

**Comment by h3adHunter** [comment]
Thanks Anton, it's working like a charm.
