### ISSUE TITLE
BooleanField doesn't work when used in "inlines".

### ISSUE THREAD

**Issue by luigibertaco** [MaistrenkoAnton/django-material-admin#62]
I am using the last version and Boolean fields when using Inlines are not working.
Both TabularInline and StackedInline have misbehavior. 

TabularInline will treat the boolean field as readonly.
StackedInline will show the changes on the first stacked record only.

I am investigating and will open a PR if I can find the issue.

**Comment by MaistrenkoAnton** [comment]
Fixed in `v1.6.21`
