### ISSUE TITLE
Bug in Top-bar Responsive

### ISSUE THREAD

**Issue by h3adHunter** [MaistrenkoAnton/django-material-admin#63]
Hi, im experiencing this bug when i open the sidemenu.

![imagen](https://user-images.githubusercontent.com/31490812/71103189-70d56400-2198-11ea-8279-9dee35edce47.png)

the buttons on the top-right dont fit well

Thanks in advance

**Comment by MaistrenkoAnton** [comment]
Fixed in version `v1.6.21`

**Comment by h3adHunter** [comment]
Yes, fixed, thanks Anton
