### ISSUE TITLE
SelectInput getting cut by Container

### ISSUE THREAD

**Issue by h3adHunter** [MaistrenkoAnton/django-material-admin#64]
Hi Anton, im experiencing the following issue when i got a select input inside a panel on a create/edit view.

![imagen](https://user-images.githubusercontent.com/31490812/71185007-5e6f2f00-2259-11ea-9b13-e52b6b9417ca.png)

when i open to select a day it looks like this, and is not letting me scroll neither.
![imagen](https://user-images.githubusercontent.com/31490812/71185022-6af38780-2259-11ea-86dc-2bb7342d708b.png)

**Comment by MaistrenkoAnton** [comment]
Fixed in `v1.6.24`
