### ISSUE TITLE
MaterialAdminTimeWidget not working properly.

### ISSUE THREAD

**Issue by luigibertaco** [MaistrenkoAnton/django-material-admin#68]
```
forms.TimeField(
    widget=widgets.MaterialAdminTimeWidget,
    disabled=True,
)
```
Will generate a time widget field with 2 icons, the first to open the popup and second to set to the current time. None of them works. However, if the user clicks on the field it does work.

It is also showing below the field instead of inside the field as the DateWidget.

**Comment by MaistrenkoAnton** [comment]
Can you give more information about the issue, from my side it works properly, couldn't reproduce it
![Screenshot from 2020-01-02 13-07-12](https://user-images.githubusercontent.com/15648919/71664380-6ce13e80-2d61-11ea-9f76-dc90b43494f1.png)

![joxi_screenshot_1577963216859](https://user-images.githubusercontent.com/15648919/71664459-b6318e00-2d61-11ea-8584-19dfaae875fe.png)

**Comment by luigibertaco** [comment]
Since last update, my date field has the same strange behaviour:

![image](https://user-images.githubusercontent.com/1386513/71693881-b08b8500-2e01-11ea-8c80-61d132bd4b58.png)

Buttons are outside of the input and don't work on my custom Form (not ModelForm) inside a Formset.

Date field was working properly before.
