### ISSUE TITLE
[Bug] Checkbox in Form checks on Label press

### ISSUE THREAD

**Issue by h3adHunter** [MaistrenkoAnton/django-material-admin#69]
Hi Anton, how are you?
I'm facing the following issue, i have a checkbox that works only when i press the label next to the square.
![imagen](https://user-images.githubusercontent.com/31490812/71833867-a4ffbe80-308c-11ea-9239-2e5a6000b4d2.png)
The red area is where it should work but it doesnt, the blue area is where is working now.

Thanks in advance

**Comment by MaistrenkoAnton** [comment]
Hello,
Fixed in `v1.6.27`
