### ISSUE TITLE
Make "collapsible-body > div a" clickable

### ISSUE THREAD

**Issue by Patataman** [MaistrenkoAnton/django-material-admin#72]
This is not really a bug or issue, but more like a pull request, but as there is no side_nav.css in the repository, I can't make you a PR.

In the original style in side_nav.min.css, the element `.collapsible-body > div` has a padding of `7px 10px 7px 53px`, making only clickable the not purple zone, instead all the div.

![imagen](https://user-images.githubusercontent.com/10652313/72454171-ac2b7880-37c0-11ea-9908-1aaa57e0bfb4.png)

Removing  `.collapsible-body > div` padding and putting it to the `.collapsible-body > div a` element made all the div clickable because now, the `a` element fill all the div.

I have tested this change and I have not felt anything out of place

Thanks.

**Comment by MaistrenkoAnton** [comment]
Fixed in `v1.6.31`
