### ISSUE TITLE
[QUESTION] Configuring images and color through MATERIAL_ADMIN_SITE

### ISSUE THREAD

**Issue by andre-filho** [MaistrenkoAnton/django-material-admin#73]
I need to **change** the default **profile picture to an image** that I have **locally**. But I can't get the picture's path right and couldn't find the solution on other issues or the README.

Also, I am having problems **changing** the **background color**. The README says that I have to specify a CSS color, but It **doesn't change** neither using the **color's name** or the **color's hex** notation.

Can you help me? What am I doing wrong?

_code_:
```python
STATIC_URL = '/static/'
LOCALE_PATHS = (PROJECT_DIR + '/locale', )

MATERIAL_ADMIN_SITE = {
    ...
    'PROFILE_PICTURE': 'img/proj_trans_l.png',
    'MAIN_BG_COLOR': '#000000',
    ...
}
```

**Comment by MaistrenkoAnton** [comment]
Does your picture accessible through `http://localhost:8000/static/img/proj_trans_l.png` ?

**Comment by MaistrenkoAnton** [comment]
According the color, seems you are using it correct. Do you have any errors in console ?

**Comment by MaistrenkoAnton** [comment]
Try to set 'MAIN_HOVER_COLOR':  '#FFFFFF',

**Comment by andre-filho** [comment]
> http://localhost:8000/static/img/proj_trans_l.png

nope, It isn't

**Comment by andre-filho** [comment]
The color solution worked, it seems like it only changes on the default theme. TY

Now I only need to solve the problem of the image.

**Comment by MaistrenkoAnton** [comment]
so you static is not configured. You should put this image into the application like `your_application/static/img/proj_trans_l.png`. After it will be accessible through url  http://localhost:8000/static/img/proj_trans_l.png, then it will work in admin configuration

**Comment by andre-filho** [comment]
> so your static is not configured. You should put this image into the application like `your_application/static/img/proj_trans_l.png`. After it will be accessible through url http://localhost:8000/static/img/proj_trans_l.png, then it will work in admin configuration

Ok, so the image path is relative to the static files' folder?

**Comment by MaistrenkoAnton** [comment]
the image should be in static

**Comment by MaistrenkoAnton** [comment]
> > so your static is not configured. You should put this image into the application like `your_application/static/img/proj_trans_l.png`. After it will be accessible through url http://localhost:8000/static/img/proj_trans_l.png, then it will work in admin configuration
> 
> Ok, so the image path is relative to the static files' folder?

Yes

**Comment by andre-filho** [comment]
Ok, thanks for your help.

Btw, is there a way that I can remove the app organizers? (See image for ref)

![image](https://user-images.githubusercontent.com/15203968/73186628-d81ef600-40fe-11ea-9c47-b1f21974f8e0.png)

**Comment by MaistrenkoAnton** [comment]
Can't understand the question

**Comment by MaistrenkoAnton** [comment]
Can you give English version

**Comment by MaistrenkoAnton** [comment]
`uthentication and Authorization` ?

**Comment by andre-filho** [comment]
Nevermind. Thanks
