### ISSUE TITLE
How to extends index.html

### ISSUE THREAD

**Issue by smartysms** [MaistrenkoAnton/django-material-admin#77]
Hi i want to extends index and base html file from material so that i can customize it further.

**Comment by MaistrenkoAnton** [comment]
Hi, you can do it as in regular django UI. Define your app under the 'admin' app in INSTALLED_APPS, and redefine template

**Comment by smartysms** [comment]
Sir if possible for you to please upload a small snippet how to do it.
Thank you.

**Comment by smartysms** [comment]
Any update on this?
