### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by gacpro** [MaistrenkoAnton/django-material-admin#8]
I've just installed `django-material-admin` following your documentation (pip install, add to installed apps and urls). However, the style is broken (see screenshots attached).

![Screen Shot 2019-04-19 at 2 52 33 PM](https://user-images.githubusercontent.com/223034/56436605-d2b09780-62b2-11e9-8845-059b3acf50af.png)
![Screen Shot 2019-04-19 at 2 52 46 PM](https://user-images.githubusercontent.com/223034/56436606-d2b09780-62b2-11e9-84b6-2f9f4d371c12.png)

**Comment by MaistrenkoAnton** [comment]
Hi, try to reinstall the latest pip, please. And follow the installation guide.

**Comment by MaistrenkoAnton** [comment]
Closed, because it's pretty old issue

**Comment by cosmin004** [comment]
Hi there. I'm also having the same issue. This might be because I also created some templates for the base django admin page. Any suggestion on how can we manage this?
