### ISSUE TITLE
Configure JS asset source

### ISSUE THREAD

**Issue by Natureshadow** [MaistrenkoAnton/django-material-admin#82]
When using materialize and jQuery on the main site already, it seems unreasonable to have another, different, copy of these libraries for the admin backend. Thus, it should be made possible to define the source URLs for third-party libraries in the settings to override those shipped with django-material-admin (of course, without any warranty that they will work).

**Comment by debdolph** [comment]
Any progress on this?

**Comment by MaistrenkoAnton** [comment]
Jquery for admin backend can be redefined in static path:
`material/admin/js/jquery.min.js`
