### ISSUE TITLE
"show_change_link = True" not working as expected

### ISSUE THREAD

**Issue by pandichef** [MaistrenkoAnton/django-material-admin#83]
[show_change_link = True](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.show_change_link) does not seem to be supported.  The icons appear on the inline formset, but it's a dead link.  (Temporary fix: In tabular.html, I changed `<td class="original">` to `<td class="">`; it changed the position of the link a bit, but at least it works.)

**Comment by MaistrenkoAnton** [comment]
Fixed in `v1.7.2`
