### ISSUE TITLE
Deleting objects with on_delete=models.CASCADE not working

### ISSUE THREAD

**Issue by pandichef** [MaistrenkoAnton/django-material-admin#84]
When I try to delete an object that would trigger a "CASCADE" deletion of related objects, I get the usual warning "Deleting the object 'thing' would require deleting the following protected related objects".  However, the button to finally delete the object (and all related objects) is not on the page at all i.e., I cannot complete the deletion via the admin UI.

**Comment by MaistrenkoAnton** [comment]
I think this is the feature of Django and totally not related to material UI, 
Does it have different behavior if you turn off material UI ?

**Comment by pandichef** [comment]
You're correct.  My apologies for any inconvenience.  Thank you
